language: rust
dist: xenial
sudo: required

notifications:
    email:
        on_success: never
        on_failure: change

rust:
    - 1.28.0

cache: cargo

before_install:
- sudo apt update
- sudo apt install -y libgtk-3-dev

before_script: cd rustemu86

script:
- cargo test
